export const queryKeys = {
  watchlist: ['alert', 'watchlist'] as const,
  dashboard: ['alert', 'dashboard'] as const,
  alertHistory: ['alert', 'history'] as const,
  predictions: ['alert', 'predict'] as const,
  alertTrend: (days: number) => ['trend', 'alert', days] as const,
  riskTrend: (name: string) => ['trend', 'risk', name] as const,
  sentimentDashboard: ['sentiment', 'dashboard'] as const,
  sentimentDetail: (name: string) => ['sentiment', 'detail', name] as const,
  contagionSummary: ['p2', 'contagion'] as const,
  contagionGraph: (name: string) => ['p2', 'contagion', name, 'graph'] as const,
  esgList: ['p2', 'esg'] as const,
  esgDetail: (name: string) => ['p2', 'esg', name] as const,
  pmi: ['analysis', 'macro', 'pmi'] as const,
  alternativeDashboard: ['analysis', 'alternatives'] as const,
  macroDetail: (name: string) => ['analysis', 'macro', name] as const,
  alternativeDetail: (name: string) => ['analysis', 'alternatives', name] as const,
  scenarioDetail: (name: string, scenario: string) =>
    ['analysis', 'scenario', name, scenario] as const,
  sanctionsDetail: (name: string) => ['analysis', 'sanctions', name] as const,
  knowledgeStats: ['knowledge', 'stats'] as const,
  knowledgeSearch: (query: string) => ['knowledge', 'search', query] as const,
  notifications: (limit?: number, read?: boolean) =>
    ['notifications', { limit, read }] as const,
  unreadCount: ['notifications', 'unread'] as const,
  sourcingRequests: ['sourcing', 'requests'] as const,
  sourcingDetail: (id: string) => ['sourcing', 'requests', id] as const,
  agentRunDetail: (id: string) => ['agent-runs', id] as const,
  suppliers: ['sourcing', 'suppliers'] as const,
  accessApplications: (status?: string) => ['sourcing', 'access-applications', status] as const,
  supplierProfile: (id: string) => ['supplier', 'profile', id] as const,
  supplierBusinessRisk: (id: string) => ['supplier', 'business-risk', id] as const,
  supplierChangelog: (id: string, limit?: number) => ['supplier', 'changelog', id, limit] as const,
} as const;
